### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by jlag34** [rndllmrn/prj-rev-bwfs-dasmoto#2]
Your CSS also looks awesome. Nice to see that you put your font family on your body for all of your children to inherit. Also, awesome work adding comments to your CSS! They made it really easy to follow your code. My only suggestion is to add a class for your span instead of adding attributes to the `span` element itself. This is because it could lead to unwanted side effects as the code base gets larger. I don’t say this about the `h1` and other headers because I feel they are phased out in exchange for creating a class that uses `font-size`.

**Comment by rndllmrn** [comment]
In regards to the <span> comments, in this instance, because the project was so small, it was ultimately fine to just give them their own attributes, but in the future as the projects get larger, it'd be best to give them their own classes for the sake of diversity, correct?

**Comment by jlag34** [comment]
Yep

**Comment by rndllmrn** [comment]
Awesome, thanks so much!
